# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kradar < Formula
  desc "Interactive Kubernetes TUI for Helm releases and image tracking"
  homepage "https://github.com/sakvarelidze/kradar"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.3/kradar_0.0.3_darwin_amd64.tar.gz"
      sha256 "46b6bc782750477f121b58dbf240d691a0f5ed903bc420d9c999e279bc9ed047"

      define_method(:install) do
        bin.install "kradar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.3/kradar_0.0.3_darwin_arm64.tar.gz"
      sha256 "13baac7914fb174fed451b1884ffb8d8f8c18943c371f56520bc0ba93697fd1c"

      define_method(:install) do
        bin.install "kradar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.3/kradar_0.0.3_linux_amd64.tar.gz"
      sha256 "7b8bbad75574922f00b2c6ef47784bb22eb63bc1eab35ccc1fbdeb2008dbd186"
      define_method(:install) do
        bin.install "kradar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.3/kradar_0.0.3_linux_arm64.tar.gz"
      sha256 "cbeecbc5d851a6f653c445414e975fab7ab2faea06e9d3694bb79a6845691066"
      define_method(:install) do
        bin.install "kradar"
      end
    end
  end

  test do
    system "#{bin}/kradar", "version"
  end
end
