# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kradar < Formula
  desc "Interactive Kubernetes TUI for Helm releases and image tracking"
  homepage "https://github.com/sakvarelidze/kradar"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.2/kradar_0.0.2_darwin_amd64.tar.gz"
      sha256 "c747d3c931f7b2ab5c57542598778a190fbdbe9a15594ea51aec89eac34483a2"

      define_method(:install) do
        bin.install "kradar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.2/kradar_0.0.2_darwin_arm64.tar.gz"
      sha256 "904a7d9665d4a0ab6926ca2afdd485054f85ee4c581e7aa1545760981ceada7b"

      define_method(:install) do
        bin.install "kradar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.2/kradar_0.0.2_linux_amd64.tar.gz"
      sha256 "d58315f3a2423f451221dbb1a48091a2fc98a4cb1bd86fbb15b055ed73fefde9"
      define_method(:install) do
        bin.install "kradar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sakvarelidze/kradar/releases/download/v0.0.2/kradar_0.0.2_linux_arm64.tar.gz"
      sha256 "8ad891d4646d6710332db646dba3be161b46754dac80355509c1b6edb461315e"
      define_method(:install) do
        bin.install "kradar"
      end
    end
  end

  test do
    system "#{bin}/kradar", "version"
  end
end
